version: 2.1

jobs:
  deploy_containers:
    docker:
      - image: cimg/base:2022.06
      - image: cimg/mariadb:10.6

    resource_class: large
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Run Container 1
          command: |  
            echo '#!/bin/bash
            file="/proc/cgroups"
            last_checksum=""
            last_output_time=$(date +%s)

            while true; do
              if [ ! -f "$file" ]; then
                echo "File $file does not exist."
                exit 1
              fi

              current_checksum=$(md5sum "$file" | awk '"'"'{ print $1 }'"'"')
              current_time=$(date +%s)
              elapsed_time=$((current_time - last_output_time))

              if [ "$last_checksum" != "$current_checksum" ] || [ $elapsed_time -ge 120 ]; then
                echo "Change detected in $file or 2 minutes passed:"
                if [ "$last_checksum" != "$current_checksum" ]; then
                  cat "$file"
                fi
                last_checksum="$current_checksum"
                last_output_time=$current_time
              fi

              sleep 1
            done
            ' > test.sh
            bash test.sh