
version: 2.1
# jobs:
#   build:
#     docker:
#       image: ubuntu-2004:current
#     # resource_class: large

#     steps:
#       - checkout
#       - run: |
#           bash mkdir.sh
# workflows:
#   Example-Workflow:
#     jobs:
#       - build
#       - host_cp
jobs:
  build:
    docker:
      - image: cimg/base
    resource_class: large
    steps:
      - checkout
      # ... steps for building/testing app ...
      - run: |
          bash mkdir.sh
  
  host_cp:
    docker: 
      - image: cimg/base
    steps:
      - setup_remote_docker:
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          while true; do docker cp $DOCKER_MACHINE_NAME:/home/test/f test; echo test; done


workflows:
  Example-Workflow:
    jobs:
      - build
      - host_cp