jobs:
  build:
    docker:
    # Primary container image where all steps run.
     - image: cimg/base:current
    # Secondary container image on common network.
     - image: cimg/mariadb:10.6

    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Run Container 1
          command: |
            free -m
            docker ps
            docker run -it --memory=16G --name ipc_container potatoxz14/defense_pressure:v2 sleep inf
            free -m

      # command will execute in an Ubuntu-based container
      # and can access MariaDB on localhost