
version: 2.1
# jobs:
#   build:
#     docker:
#       image: ubuntu-2004:current
#     # resource_class: large

#     steps:
#       - checkout
#       - run: |
#           bash mkdir.sh
# workflows:
#   Example-Workflow:
#     jobs:
#       - build
#       - host_cp
jobs:
  docker_cp:
    docker:
      - image: potatoxz14/docker_cp:v0
    resource_class: large
    steps:
      # - checkout
      # ... steps for building/testing app ...
      - run: |
          cd /home
          free -m
          sudo mkdir test
          sudo ./symbol a &
          free -m
      - setup_remote_docker:
          docker_layer_caching: true
      # Install via apk on alpine based images
      # - run:
      #     name: Install Docker client
      #     command: apk add docker-cli

      # build and push Docker image
      - checkout
      - run: |
          free -m
          container_id=$(docker ps | grep potatoxz14/docker_cp:v0 | awk 'NR==1{print $1}')
          echo $container_id
          ./docker_cp_while.sh
      # docker ps
      
  # host_cp:
  #   docker: 
  #     - image: potatoxz14/docker_cp:v0
  #   steps:
  #     - setup_remote_docker:
  #         docker_layer_caching: true

  #     # build and push Docker image
  #     - run: |
  #         while true; do docker cp $DOCKER_MACHINE_NAME:/home/test/f test; echo test; done


workflows:
  Example-Workflow:
    jobs:
      # - build
      - docker_cp