jobs:
  build:
    docker:
    # Primary container image where all steps run.
     - image: cimg/base:current
    # Secondary container image on common network.
     - image: cimg/mariadb:10.6

    steps:
      - checkout
      - run:
          name: Run Container 1
          command: |
            docker ps
      # command will execute in an Ubuntu-based container
      # and can access MariaDB on localhost